# Generated by Django 5.1 on 2024-11-03 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorSection', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='dist',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='long',
        ),
        migrations.AddField(
            model_name='hospital',
            name='district',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
