# Generated by Django 5.1 on 2024-11-03 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorSection', '0002_remove_hospital_dist_remove_hospital_lat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='long',
        ),
        migrations.AddField(
            model_name='doctors',
            name='district',
            field=models.CharField(default='default', max_length=200),
        ),
        migrations.AddField(
            model_name='doctors',
            name='location',
            field=models.CharField(default='default', max_length=200),
        ),
    ]
